// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quiz_Master_SQL.Quiz_Master_SQL.Data;

#nullable disable

namespace Quiz_Master_SQL.Migrations
{
    [DbContext(typeof(QuizMasterDbContext))]
    [Migration("20250810174721_Init13")]
    partial class Init13
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.ConfigTableDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("MaxQuizId")
                        .HasColumnType("bigint");

                    b.Property<long>("MaxUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ConfigTablesDB");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5ba9cd6e-1a8a-4c08-a9a3-bd195dc05a49"),
                            MaxQuizId = 0L,
                            MaxUserId = 10L
                        });
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.FavoritedQuizzeDB", b =>
                {
                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("QuizId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("FavoritedQuizzes");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.FinishedChallengeDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChallengeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FinishedChallengesDB");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.LikedQuizzeDB", b =>
                {
                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("QuizId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("LikedQuizzesDB");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.MatchingPairsQuestionDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Num")
                        .HasColumnType("bigint");

                    b.Property<long>("Point")
                        .HasColumnType("bigint");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("MatchingPairsQuestionDB");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.MessagesDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.MultipleChoiceQuestionDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Num")
                        .HasColumnType("bigint");

                    b.Property<long>("Point")
                        .HasColumnType("bigint");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("MultipleChoiceQuestionDB");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.MultiplyAnswersDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MPQCorrectAnswerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MPQFirstAnswerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MPQSecondAnswerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MultipleChoiceQuestionCorrectAnswerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MultipleChoiceQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SingleChoiceQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MPQCorrectAnswerId");

                    b.HasIndex("MPQFirstAnswerId");

                    b.HasIndex("MPQSecondAnswerId");

                    b.HasIndex("MultipleChoiceQuestionCorrectAnswerId");

                    b.HasIndex("MultipleChoiceQuestionId");

                    b.HasIndex("SingleChoiceQuestionId");

                    b.ToTable("MultiplyAnswers");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.QuizDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Likes")
                        .HasColumnType("bigint");

                    b.Property<long>("NumOfQuestions")
                        .HasColumnType("bigint");

                    b.Property<string>("QuizName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuizStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("QuizzesDB");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.ShortAnswerQuestionDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Num")
                        .HasColumnType("bigint");

                    b.Property<long>("Point")
                        .HasColumnType("bigint");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("ShortAnswerQuestions");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.SingleChoiceQuestionDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Num")
                        .HasColumnType("bigint");

                    b.Property<long>("Point")
                        .HasColumnType("bigint");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("SingleChoiceQuestions");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.TrueOrFalseQuestionDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Answer")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Num")
                        .HasColumnType("bigint");

                    b.Property<long>("Point")
                        .HasColumnType("bigint");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("TrueOrFalseQuestions");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.UserDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("Level")
                        .HasColumnType("bigint");

                    b.Property<long?>("NumberCreatedQuizzes")
                        .HasColumnType("bigint");

                    b.Property<long?>("NumberCreatedQuizzesChallengers")
                        .HasColumnType("bigint");

                    b.Property<long?>("NumberFavoriteQuizzes")
                        .HasColumnType("bigint");

                    b.Property<long?>("NumberFinishedChallenges")
                        .HasColumnType("bigint");

                    b.Property<long?>("NumberLikedQuizzes")
                        .HasColumnType("bigint");

                    b.Property<long?>("NumberSolvedNormalQuizzes")
                        .HasColumnType("bigint");

                    b.Property<long?>("NumberSolvedTestQuizzes")
                        .HasColumnType("bigint");

                    b.Property<long>("Password")
                        .HasColumnType("bigint");

                    b.Property<long?>("Points")
                        .HasColumnType("bigint");

                    b.Property<long>("UserGameId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserOptions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UsersDB");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f7b651d-0fba-4321-9f2d-4badb7e2ec81"),
                            FirstName = "Admin",
                            LastName = "One",
                            Password = 708698343L,
                            UserGameId = 1L,
                            UserName = "admin1",
                            UserOptions = 1
                        },
                        new
                        {
                            Id = new Guid("f21cb56b-a1bd-4880-b186-03e781ae7157"),
                            FirstName = "Admin",
                            LastName = "Two",
                            Password = 708698342L,
                            UserGameId = 2L,
                            UserName = "admin2",
                            UserOptions = 1
                        },
                        new
                        {
                            Id = new Guid("f4111ed6-c886-4d34-81cd-63d5fdfaf016"),
                            FirstName = "Admin",
                            LastName = "Three",
                            Password = 708698337L,
                            UserGameId = 3L,
                            UserName = "admin3",
                            UserOptions = 1
                        },
                        new
                        {
                            Id = new Guid("3031f5e6-6845-419a-8ddf-abbc563e8dda"),
                            FirstName = "Admin",
                            LastName = "Four",
                            Password = 708698336L,
                            UserGameId = 4L,
                            UserName = "admin4",
                            UserOptions = 1
                        },
                        new
                        {
                            Id = new Guid("9b781b62-bb61-4c3c-8997-6321d474cade"),
                            FirstName = "Admin",
                            LastName = "Five",
                            Password = 708698339L,
                            UserGameId = 5L,
                            UserName = "admin5",
                            UserOptions = 1
                        },
                        new
                        {
                            Id = new Guid("9d5c7622-fd27-494f-85b8-bd8bb2cde748"),
                            FirstName = "Admin",
                            LastName = "Six",
                            Password = 708698338L,
                            UserGameId = 6L,
                            UserName = "admin6",
                            UserOptions = 1
                        },
                        new
                        {
                            Id = new Guid("6723fd1c-8128-4b36-808d-1053137ac351"),
                            FirstName = "Admin",
                            LastName = "Seven",
                            Password = 708698349L,
                            UserGameId = 7L,
                            UserName = "admin7",
                            UserOptions = 1
                        },
                        new
                        {
                            Id = new Guid("51594435-7d14-4084-9798-d4d2348f3cb9"),
                            FirstName = "Admin",
                            LastName = "Eight",
                            Password = 708698348L,
                            UserGameId = 8L,
                            UserName = "admin8",
                            UserOptions = 1
                        },
                        new
                        {
                            Id = new Guid("0ac7744c-6d09-4287-8dd9-ae942b12f1b0"),
                            FirstName = "Admin",
                            LastName = "Nine",
                            Password = 708698351L,
                            UserGameId = 9L,
                            UserName = "admin9",
                            UserOptions = 1
                        },
                        new
                        {
                            Id = new Guid("374a1961-cff2-44ee-9cc4-333698ad0d81"),
                            FirstName = "Admin",
                            LastName = "Ten",
                            Password = 2021029294L,
                            UserGameId = 10L,
                            UserName = "admin10",
                            UserOptions = 1
                        });
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.FavoritedQuizzeDB", b =>
                {
                    b.HasOne("Quiz_Master_SQL.Data.Models.QuizDB", "Quiz")
                        .WithMany("FavoritedQuizzes")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Quiz_Master_SQL.Data.Models.UserDB", "User")
                        .WithMany("FavoritedQuizzes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.FinishedChallengeDB", b =>
                {
                    b.HasOne("Quiz_Master_SQL.Data.Models.UserDB", "UserDBs")
                        .WithMany("FinishedChallenges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserDBs");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.LikedQuizzeDB", b =>
                {
                    b.HasOne("Quiz_Master_SQL.Data.Models.QuizDB", "QuizDBs")
                        .WithMany("LikedQuizzes")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Quiz_Master_SQL.Data.Models.UserDB", "UserDBs")
                        .WithMany("LikedQuizzes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizDBs");

                    b.Navigation("UserDBs");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.MatchingPairsQuestionDB", b =>
                {
                    b.HasOne("Quiz_Master_SQL.Data.Models.QuizDB", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.MessagesDB", b =>
                {
                    b.HasOne("Quiz_Master_SQL.Data.Models.UserDB", "UserDB")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserDB");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.MultipleChoiceQuestionDB", b =>
                {
                    b.HasOne("Quiz_Master_SQL.Data.Models.QuizDB", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.MultiplyAnswersDB", b =>
                {
                    b.HasOne("Quiz_Master_SQL.Data.Models.MatchingPairsQuestionDB", "MPQCorrectAnswer")
                        .WithMany("MatchingPairsCorrectAnswers")
                        .HasForeignKey("MPQCorrectAnswerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Quiz_Master_SQL.Data.Models.MatchingPairsQuestionDB", "MPQFirstAnswer")
                        .WithMany("MatchingPairsFirstAnswers")
                        .HasForeignKey("MPQFirstAnswerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Quiz_Master_SQL.Data.Models.MatchingPairsQuestionDB", "MPQSecondAnswer")
                        .WithMany("MatchingPairsSecondAnswers")
                        .HasForeignKey("MPQSecondAnswerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Quiz_Master_SQL.Data.Models.MultipleChoiceQuestionDB", "MultipleChoiceQuestionCorrectAnswer")
                        .WithMany("MultiplyCorrectAnswers")
                        .HasForeignKey("MultipleChoiceQuestionCorrectAnswerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Quiz_Master_SQL.Data.Models.MultipleChoiceQuestionDB", "MultipleChoiceQuestion")
                        .WithMany("MultiplyAnswers")
                        .HasForeignKey("MultipleChoiceQuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Quiz_Master_SQL.Data.Models.SingleChoiceQuestionDB", "SingleChoiceQuestion")
                        .WithMany("MultiplyAnswers")
                        .HasForeignKey("SingleChoiceQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MPQCorrectAnswer");

                    b.Navigation("MPQFirstAnswer");

                    b.Navigation("MPQSecondAnswer");

                    b.Navigation("MultipleChoiceQuestion");

                    b.Navigation("MultipleChoiceQuestionCorrectAnswer");

                    b.Navigation("SingleChoiceQuestion");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.QuizDB", b =>
                {
                    b.HasOne("Quiz_Master_SQL.Data.Models.UserDB", "UserDb")
                        .WithMany("CreatedQuizzes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserDb");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.ShortAnswerQuestionDB", b =>
                {
                    b.HasOne("Quiz_Master_SQL.Data.Models.QuizDB", "Quiz")
                        .WithMany("ShortAnswerQuestions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.SingleChoiceQuestionDB", b =>
                {
                    b.HasOne("Quiz_Master_SQL.Data.Models.QuizDB", "Quiz")
                        .WithMany("SingleChoiceQuestions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.TrueOrFalseQuestionDB", b =>
                {
                    b.HasOne("Quiz_Master_SQL.Data.Models.QuizDB", "Quiz")
                        .WithMany("TrueOrFalseQuestions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.MatchingPairsQuestionDB", b =>
                {
                    b.Navigation("MatchingPairsCorrectAnswers");

                    b.Navigation("MatchingPairsFirstAnswers");

                    b.Navigation("MatchingPairsSecondAnswers");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.MultipleChoiceQuestionDB", b =>
                {
                    b.Navigation("MultiplyAnswers");

                    b.Navigation("MultiplyCorrectAnswers");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.QuizDB", b =>
                {
                    b.Navigation("FavoritedQuizzes");

                    b.Navigation("LikedQuizzes");

                    b.Navigation("ShortAnswerQuestions");

                    b.Navigation("SingleChoiceQuestions");

                    b.Navigation("TrueOrFalseQuestions");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.SingleChoiceQuestionDB", b =>
                {
                    b.Navigation("MultiplyAnswers");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.UserDB", b =>
                {
                    b.Navigation("CreatedQuizzes");

                    b.Navigation("FavoritedQuizzes");

                    b.Navigation("FinishedChallenges");

                    b.Navigation("LikedQuizzes");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
