// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quiz_Master_SQL.Quiz_Master_SQL.Data;

#nullable disable

namespace Quiz_Master_SQL.Migrations
{
    [DbContext(typeof(QuizMasterDbContext))]
    [Migration("20250815151046_Init15")]
    partial class Init15
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.ConfigTableDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("MaxQuizId")
                        .HasColumnType("bigint");

                    b.Property<long>("MaxUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ConfigTablesDB");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.FavoritedQuizzeDB", b =>
                {
                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("QuizId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("FavoritedQuizzes");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.FinishedChallengeDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChallengeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FinishedChallengesDB");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.LikedQuizzeDB", b =>
                {
                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("QuizId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("LikedQuizzesDB");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.MatchingPairsQuestionDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Num")
                        .HasColumnType("bigint");

                    b.Property<long>("Point")
                        .HasColumnType("bigint");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("MatchingPairsQuestionDB");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.MessagesDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.MultipleChoiceQuestionDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Num")
                        .HasColumnType("bigint");

                    b.Property<long>("Point")
                        .HasColumnType("bigint");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("MultipleChoiceQuestionDB");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.MultiplyAnswersDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MPQCorrectAnswerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MPQFirstAnswerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MPQSecondAnswerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MultipleChoiceQuestionCorrectAnswerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MultipleChoiceQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SingleChoiceQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MPQCorrectAnswerId");

                    b.HasIndex("MPQFirstAnswerId");

                    b.HasIndex("MPQSecondAnswerId");

                    b.HasIndex("MultipleChoiceQuestionCorrectAnswerId");

                    b.HasIndex("MultipleChoiceQuestionId");

                    b.HasIndex("SingleChoiceQuestionId");

                    b.ToTable("MultiplyAnswers");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.QuizDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.Property<long>("Likes")
                        .HasColumnType("bigint");

                    b.Property<long>("NumOfQuestions")
                        .HasColumnType("bigint");

                    b.Property<string>("QuizName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuizStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("QuizzesDB");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.ShortAnswerQuestionDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Num")
                        .HasColumnType("bigint");

                    b.Property<long>("Point")
                        .HasColumnType("bigint");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("ShortAnswerQuestions");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.SingleChoiceQuestionDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Num")
                        .HasColumnType("bigint");

                    b.Property<long>("Point")
                        .HasColumnType("bigint");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("SingleChoiceQuestions");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.TrueOrFalseQuestionDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Answer")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Num")
                        .HasColumnType("bigint");

                    b.Property<long>("Point")
                        .HasColumnType("bigint");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("TrueOrFalseQuestions");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.UserDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("Level")
                        .HasColumnType("bigint");

                    b.Property<long?>("NumberCreatedQuizzes")
                        .HasColumnType("bigint");

                    b.Property<long?>("NumberCreatedQuizzesChallengers")
                        .HasColumnType("bigint");

                    b.Property<long?>("NumberFavoriteQuizzes")
                        .HasColumnType("bigint");

                    b.Property<long?>("NumberFinishedChallenges")
                        .HasColumnType("bigint");

                    b.Property<long?>("NumberLikedQuizzes")
                        .HasColumnType("bigint");

                    b.Property<long?>("NumberSolvedNormalQuizzes")
                        .HasColumnType("bigint");

                    b.Property<long?>("NumberSolvedTestQuizzes")
                        .HasColumnType("bigint");

                    b.Property<long>("Password")
                        .HasColumnType("bigint");

                    b.Property<long?>("Points")
                        .HasColumnType("bigint");

                    b.Property<long>("UserGameId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserOptions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UsersDB");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.FavoritedQuizzeDB", b =>
                {
                    b.HasOne("Quiz_Master_SQL.Data.Models.QuizDB", "Quiz")
                        .WithMany("FavoritedQuizzes")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Quiz_Master_SQL.Data.Models.UserDB", "User")
                        .WithMany("FavoritedQuizzes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.FinishedChallengeDB", b =>
                {
                    b.HasOne("Quiz_Master_SQL.Data.Models.UserDB", "UserDBs")
                        .WithMany("FinishedChallenges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserDBs");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.LikedQuizzeDB", b =>
                {
                    b.HasOne("Quiz_Master_SQL.Data.Models.QuizDB", "QuizDBs")
                        .WithMany("LikedQuizzes")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Quiz_Master_SQL.Data.Models.UserDB", "UserDBs")
                        .WithMany("LikedQuizzes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizDBs");

                    b.Navigation("UserDBs");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.MatchingPairsQuestionDB", b =>
                {
                    b.HasOne("Quiz_Master_SQL.Data.Models.QuizDB", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.MessagesDB", b =>
                {
                    b.HasOne("Quiz_Master_SQL.Data.Models.UserDB", "UserDB")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserDB");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.MultipleChoiceQuestionDB", b =>
                {
                    b.HasOne("Quiz_Master_SQL.Data.Models.QuizDB", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.MultiplyAnswersDB", b =>
                {
                    b.HasOne("Quiz_Master_SQL.Data.Models.MatchingPairsQuestionDB", "MPQCorrectAnswer")
                        .WithMany("MatchingPairsCorrectAnswers")
                        .HasForeignKey("MPQCorrectAnswerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Quiz_Master_SQL.Data.Models.MatchingPairsQuestionDB", "MPQFirstAnswer")
                        .WithMany("MatchingPairsFirstAnswers")
                        .HasForeignKey("MPQFirstAnswerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Quiz_Master_SQL.Data.Models.MatchingPairsQuestionDB", "MPQSecondAnswer")
                        .WithMany("MatchingPairsSecondAnswers")
                        .HasForeignKey("MPQSecondAnswerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Quiz_Master_SQL.Data.Models.MultipleChoiceQuestionDB", "MultipleChoiceQuestionCorrectAnswer")
                        .WithMany("MultiplyCorrectAnswers")
                        .HasForeignKey("MultipleChoiceQuestionCorrectAnswerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Quiz_Master_SQL.Data.Models.MultipleChoiceQuestionDB", "MultipleChoiceQuestion")
                        .WithMany("MultiplyAnswers")
                        .HasForeignKey("MultipleChoiceQuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Quiz_Master_SQL.Data.Models.SingleChoiceQuestionDB", "SingleChoiceQuestion")
                        .WithMany("MultiplyAnswers")
                        .HasForeignKey("SingleChoiceQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MPQCorrectAnswer");

                    b.Navigation("MPQFirstAnswer");

                    b.Navigation("MPQSecondAnswer");

                    b.Navigation("MultipleChoiceQuestion");

                    b.Navigation("MultipleChoiceQuestionCorrectAnswer");

                    b.Navigation("SingleChoiceQuestion");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.QuizDB", b =>
                {
                    b.HasOne("Quiz_Master_SQL.Data.Models.UserDB", "UserDb")
                        .WithMany("CreatedQuizzes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserDb");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.ShortAnswerQuestionDB", b =>
                {
                    b.HasOne("Quiz_Master_SQL.Data.Models.QuizDB", "Quiz")
                        .WithMany("ShortAnswerQuestions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.SingleChoiceQuestionDB", b =>
                {
                    b.HasOne("Quiz_Master_SQL.Data.Models.QuizDB", "Quiz")
                        .WithMany("SingleChoiceQuestions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.TrueOrFalseQuestionDB", b =>
                {
                    b.HasOne("Quiz_Master_SQL.Data.Models.QuizDB", "Quiz")
                        .WithMany("TrueOrFalseQuestions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.MatchingPairsQuestionDB", b =>
                {
                    b.Navigation("MatchingPairsCorrectAnswers");

                    b.Navigation("MatchingPairsFirstAnswers");

                    b.Navigation("MatchingPairsSecondAnswers");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.MultipleChoiceQuestionDB", b =>
                {
                    b.Navigation("MultiplyAnswers");

                    b.Navigation("MultiplyCorrectAnswers");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.QuizDB", b =>
                {
                    b.Navigation("FavoritedQuizzes");

                    b.Navigation("LikedQuizzes");

                    b.Navigation("ShortAnswerQuestions");

                    b.Navigation("SingleChoiceQuestions");

                    b.Navigation("TrueOrFalseQuestions");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.SingleChoiceQuestionDB", b =>
                {
                    b.Navigation("MultiplyAnswers");
                });

            modelBuilder.Entity("Quiz_Master_SQL.Data.Models.UserDB", b =>
                {
                    b.Navigation("CreatedQuizzes");

                    b.Navigation("FavoritedQuizzes");

                    b.Navigation("FinishedChallenges");

                    b.Navigation("LikedQuizzes");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
